### ISSUE TITLE
Some Bugs - Heads up!

### ISSUE THREAD

**Issue by stelian87** [atanasster/grommet-nextjs#11]
Heads up! At first glance:
* Broken link: 
Style -> Theme Designer
 https://grommet-nextjs.herokuapp.com/theme?theme=hp
grommet-controls -> tag ->icon
https://grommet-nextjs.herokuapp.com/examples/grommet-controls/Tag/icon?theme=hp

* hpe map gone! as intended?
* broken images: Style ->Design kit

i'm writing this in hopes it helps you... i'm loving the new site format and thank you for your good work! cheers!

**Comment by atanasster** [comment]
Thanks a lot @stelian87 - i really appreciate you taking the time to help me. Will be fixing those one by one and will try to finish the new content before next week.

**Comment by atanasster** [comment]
Hi @stelian87 - I am finishing the new site and fixed most of the issues. I will close this one as those issues have been fixed. 

However, I would really appreciate it if you can give it a test and enter new issues if you find bugs or have some enhancement ideas.
