### ISSUE TITLE
Theme - Persist into localStorage

### ISSUE THREAD

**Issue by stelian87** [atanasster/grommet-nextjs#12]
hello,
as the tittle implies i've been trying all morning to persist into localStorage the themes state.
the code:
**import { loadState, saveState } from "./localStorage";
...
const persistedState = loadState();

export const store = createStore(
  makeStore,
  //initialState,
  persistedState,
  composeWithDevTools(applyMiddleware(thunkMiddleware))
);

store.subscribe(() => {
  saveState({
    themes: store.getState().themes
  });
});**

and with this localStorage.js:
**export const loadState = () => {
  try {
    const serializedState = localStorage.getItem("state");
    if (serializedState === null) {
      return {};
    }
    return JSON.parse(serializedState);
  } catch (err) {
    return {};
  }
};

export const saveState = state => {
  try {
    const serializedState = JSON.stringify(state);
    localStorage.setItem("state", serializedState);
  } catch (err) {
    console.log(err);
  }
};**

I've had no success with errors like on F5, page refresh:
VM479 main.js:11068 Warning: Prop `className` did not match. Server: "StyledButton-sc-323bzc-0 cHDXap" Client: "StyledButton-sc-323bzc-0 fRAxrl"
It looks like you've wrapped styled() around your React component (button), but the className prop is not being passed down to a child. No styles will be rendered unless className is composed within your React component.

Did you face this? i've tried every which way and i'm puzzled

**Comment by atanasster** [comment]
Hi @stelian87 - i also,have the styled-components warning in developmemnt mode with nextjs, but its been pretymharmless so far and i havent much investigated.

Besides the warning -,what other issue do you have exactly - can you possibly create a codesandbox?

**Comment by stelian87** [comment]
i'm also testing on development build.
The problem is visual. the styles break.

![loacalstorage](https://user-images.githubusercontent.com/44492585/52568281-fa990000-2e16-11e9-87cf-99e180aab343.jpg)

**Comment by stelian87** [comment]
@atanasster i think it's easier to reproduce on your code if you have the time.
basically instead of const initialState = {}; you pass the persistedState in ../redux/index.js. 
the code is in the initial comment

**Comment by atanasster** [comment]
@stelian87 - it should work, some possible issues:

1. Are you rendering server side (in this case local storage is not accessible SSR) and you might opt to use cookies or something like that.
2. I am not entirely sure about your redux lifecycle methods, but I tried just replacing the initialState and it worked (and saving the local storage every time a reduce ACTION is triggered that modifies it) 
```
if (process.browser) {
  initialState = { ...initialState, ...getItem('theme') };
}
```
Anyway, I would be pretty confident something in your save/load process is amiss

**Comment by stelian87** [comment]
after several tries i did not get this to work. it seems that on F5 the localStorage becomes undefined. Seeing as i only want to persist the theme and it's not so important, i will put this on hold.
i will return with a comment if i manage it either with local storage or react-persist or another solution.
Please close the issue.

**Comment by atanasster** [comment]
thanks for the update, let me know how it turns out
