### ISSUE TITLE
Adding wrap-reverse to flexbox

### ISSUE THREAD

**Issue by ShimiSun** [atanasster/grommet-nextjs#15]
It will be fun to include `wrap-reverse` option in the playground.
I believe it will require to replace the current ChecBox to probably a dropdown(?)
https://github.com/atanasster/grommet-nextjs/blob/ed03232e575cbc255eb71245c3855a903b028da7/components/markdown/FlexBox.js#L158

linked to https://github.com/grommet/grommet/issues/2754

The playground looks GREAT

**Comment by atanasster** [comment]
Great job @ShimiSun , the site is now updated with wrap: row-reverse.
