### ISSUE TITLE
PagingTable - Fetching data manually 

### ISSUE THREAD

**Issue by stelian87** [atanasster/grommet-nextjs#3]
Hello,
First off if this does not belong here please delete it. I am hopeful that you'll help me d'ow.

My situation is as fallows: i'm trying to use the PagingTable component and load the data manually calling an API and passing the page and pageSize as query params, as i don't want to get all my records in one pull. Although the Next button is enabled there is no action performed on click and i can't call the API with the next page param.

What can i do? Thank you kindly. 

P.S. after some digging on your documentation ("Derived from https://github.com/react-tools/react-table.") i managed to solve it. Thank you nevertheless!!!

**Comment by atanasster** [comment]
Hi glad to hear you solved it :) yes the react table documentation is usually the go to place

Cheers
