### ISSUE TITLE
PagingTable - Cell overflow  

### ISSUE THREAD

**Issue by stelian87** [atanasster/grommet-nextjs#4]
Hello,

In react table when the cell overflows the missing text is replaced with the customary "...". However in PagingTable the behavior is not the same. How can i achieve this behavior?

i have tried for columns prop:
...
Cell: row => (
      <span
        style={{
          overflow: "hidden",
          textOverflow: "ellipsis",
          whiteSpace: "nowrap"
        }}
      >
        {row.value}
      </span>
    )

P.S. Also how can i highlight the row on mouse over?

**Comment by stelian87** [comment]
managed it with:
Cell: row => (
      <div
        style={{
          overflow: "hidden",
          textOverflow: "ellipsis",
          whiteSpace: "nowrap"
        }}
      >
        {row.value}
      </div>
    )

still struggling with general decorations:
  cell: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap"
  },

Also can't seem to find a solution for row hover:
row: {
    hover: {
      background: { color: "brand" }
    }
  }

**Comment by atanasster** [comment]
Hi @stelian87 - did you get it working?

**Comment by stelian87** [comment]
> Hi @stelian87 - did you get it working?

hello
1. Overflow
Not how i would like. I have to add the style for each cell in the row.
Can't i do it in the decorations -> cell prop?

2. Highlight 
Nope. PagingTable doesn't accept className like react table. And i couldn't get it to work with decorations -> row prop either

**Comment by atanasster** [comment]
@stelian87 
1. for the overflow of text you can use: 
```
decorations={{
  cell: { truncate: true },
}}
```

2. Highlight on hover - I am making a few changes and will push a new version

**Comment by atanasster** [comment]
@stelian87 - just published grommet-controls 1.0.7 with hover support.

Here is a CodeSandbox: https://codesandbox.io/s/8ymv342nl2

you can set hover by using the theme.global.hover props:
```
decorations={{
  row: { hover: true }
}}
```

or you can supply your own hover props: 
```
decorations={{
  row: { hover: { background: "black", color: "red" } }
}}
```

**Comment by stelian87** [comment]
First of all i'd like to thank you for taking the time to help the community.
I have tried the first fix and works perfectly.
For the 2nd fix i'm having a little trouble with the packages. 

I have seen the code in codesandbox and i have no doubt it works.
I consider the problem answered.
Thank you again and wish you a good day!

**Comment by atanasster** [comment]
Thanks for the feedback. It seems the package was not updated - the first fix works with older versions of grommet-controls and only the hover styling requires the latest grommet-controls. 

Let me know if you keep having issues upgrading the packages.
Have a great day as well

**Comment by stelian87** [comment]
I have updated to 1.0.7 and works but it cancels rowOdd property. Tried it on your codesandbox.
Is this intended?

**Comment by atanasster** [comment]
Ah, great to hear the versions are ok

rowOdd/rowEven - you can add the hover style there instead of row. Currently, if row is specified, then it has precedence over rowOdd/rowEeven

I can also make a change to merge both row and rowOdd props - what do you think?

**Comment by stelian87** [comment]
Well you have to decide. This is what i have:

rowOdd: {
    background: { color: "light-3", opacity: "medium" }
  },
row: { hover: { background: "light-4" } }

and i would expect the behavior to be:
odd rows to be colored differently and on hover to have a 3rd color.
This is the usual idea to improve user experience, for a light read.

If it's too much work i'll chose between the 2.

**Comment by atanasster** [comment]
yes, I will push an update soon, also looking at SelectInput

**Comment by atanasster** [comment]
@stelian87 - 1.0.8 released to merge row and rowOdd decorations:
https://codesandbox.io/s/8ymv342nl2

**Comment by stelian87** [comment]
this worked perfectly
