### ISSUE TITLE
Form - SelectField Incomplete

### ISSUE THREAD

**Issue by stelian87** [atanasster/grommet-nextjs#5]
hello again,
I'm working on a Form with some mapped SelectFields from a json.
I've noticed the following:
- the SelectField control does not inherit the onChange prop from the parent Form control(i.e. TextInputField, CheckBoxField)
- the SelectField control does not pass all it's props on the event.target for onChange(i.e. name) which can be used when setting the state of value of that SelectField. The "correct" behavior can be noticed on components such as TextInputField, CheckBoxField.

Can you check this?

**Comment by atanasster** [comment]
Can you please make it into a codesandbox, i am not sure i understand the issue

**Comment by stelian87** [comment]
this is what i have in codesandbox:
https://codesandbox.io/s/w0yz1x8no8

now you can see in console that when you trigger the event on change for the text input you log in console event.target which has all the props of the text input control.

Also the text input control pings the onChange from the Form control

**Comment by atanasster** [comment]
@stelian87 , please install 1.0.8:

here is an example, I think it does what you had in mind
https://codesandbox.io/s/mzr70w3z5j

**Comment by stelian87** [comment]
in codesandbox it works great but in my code there's an error:
withFormField.js:31 Uncaught TypeError: Cannot read property 'value' of null
    at GrommetField._this.onChange (withFormField.js:31)
    at onSelectChange (Select.js:126)
    at SelectContainer.selectOption (SelectContainer.js:110)
    at __WEBPACK_IMPORTED_MODULE_0_react___default.a.createElement.onClick (SelectContainer.js:393)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
    at invokeGuardedCallback (react-dom.development.js:256)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:270)
    at executeDispatch (react-dom.development.js:561)
    at executeDispatchesInOrder (react-dom.development.js:583)

I guess it's the packages again... will investigate and come back

**Comment by stelian87** [comment]
![new bitmap image](https://user-images.githubusercontent.com/44492585/50833180-17926d00-1359-11e9-84ab-728aec474a1b.jpg)

the target prop is set to null. can you help me here?

**Comment by atanasster** [comment]
@stelian87 my guess would be that you are using a slightly older version of grommet, where the Select component did not have a 'target' property on the event parameter.
Anyway, I uploaded a new version 1.0.9 where it checks if target is null or not.

**Comment by stelian87** [comment]
@atanasster 
hello
sorry for the late response. yesterday i took a personal day

After i saw i still had errors i updated to 2.2.1. on grommet and i'm now getting the behavior from codesandbox.
However something is still off.
Check this out when i set a default value: https://codesandbox.io/s/py4nwlym3m 

I handled my code to work as is, so if you don't have the time it's ok. Just want to give you feedback.

**Comment by atanasster** [comment]
@stelian87 thanks for reporting this. 

It seems there is a slight misunderstanding - to set default values for a form, you need to supply an `object` property to form, instead of accessing directly the value prop of the field.

Here is a modified example: 
https://codesandbox.io/s/9jymvkn5ro

**Comment by stelian87** [comment]
@atanasster thanks for this solution.
I can't use this sadly because the behavior is not how i'd like.
My order of the methods till now:
1. set the initial state in the constructor
2. render()
3. componentDidMount()
4. setState()
5. render()
With the object prop the values load at step 2 with the initial values(current state with empty values). After the component mounts and the state is changed, the object prop of the Form does not get the new state.
Somehow it's not the case with the value prop.

P.S. Again, my case is that in the componentDidMount i'm fetching data async from a WEB API and i'm updating the state of the data.
