### ISSUE TITLE
Form - object prop

### ISSUE THREAD

**Issue by stelian87** [atanasster/grommet-nextjs#7]
Hello again,

I was wandering if you can help me with the fallowing issue.
The object prop of Form isn't set on setState, unlike value prop of TextInputField. I wrote the code in codesandbox: https://codesandbox.io/s/vq2jnm0nxy
This affects the validations as well.The form is invalid based on initial empty values.
Do you have any suggestions on how to change the code?
  
P.s. i have tried to figure it on my own with no result.

**Comment by stelian87** [comment]
I think i found a way using a loading state.If the date is found loading is false.
And in render i render the form only if loading if false. Validation works perfectly now.

let me know if there's a more elegant way to do this. if not please close this issue.

**Comment by atanasster** [comment]
@stelian87 thanks a lot for taking the time to submit. I am currently not working on my forms and haven't had time to test many real use-cases recently.
It is an actual issue - support for async loading of default values should be handled more 'natural'.

I have updated now to grommet-controls 1.0.10, can you please also update and let me know how it works for you. Here is also the code sandbox: https://codesandbox.io/s/8l8k27o9v8

**Comment by atanasster** [comment]
I added also the example to the web site 
https://grommet-nextjs.herokuapp.com/examples/Form/object

**Comment by stelian87** [comment]
it works beautifully!
fewer lines of code...it's much appreciated! Thanks!

**Comment by atanasster** [comment]
Cool, thanks
