### ISSUE TITLE
Theme - Without routing

### ISSUE THREAD

**Issue by stelian87** [atanasster/grommet-nextjs#8]
Hello,
was wondering if there's a way to implement theme without the url query param "theme".
My guess is that the change must be done at the Header level with the react feature Context?

i simply don't want to have to handle the url on every component; i want to stored the selected theme globally with the possibility to update. I am looking into Context to do this.

Edited: i have managed it using basic state and removing routing code. i'm happy with it.
Closing and keeping for future reference.

**Comment by atanasster** [comment]
Hi @stelian87 i wanted the theme selection to be persistant, thats why i am using the url. If you have some other way to persist settings (a backend database) you can use that as well. 
The react Context - you can replace my use of the redux store with that.
